fragment HomeParts on Home {
  __typename
  brandName
  heroImages
}

fragment AboutParts on About {
  __typename
  title
  portraitImage
  body
}

fragment ConnectParts on Connect {
  __typename
  title
  sections {
    __typename
    title
    name
    address
    email
    link
    linkText
  }
}

fragment ProjectsParts on Projects {
  __typename
  title
  year
  coverImage
  images
  description
  category
  order
  body
}

fragment WritingParts on Writing {
  __typename
  title
  date
  author
  description
  coverImage
  body
}
